"""empty message

Revision ID: 6100c668c160
Revises: e160f6419e45
Create Date: 2021-11-01 20:31:02.017680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6100c668c160'
down_revision = 'e160f6419e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asin', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.Column('rating_num', sa.String(length=10), nullable=True),
    sa.Column('price', sa.String(length=15), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('add__search',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add__search')
    op.drop_table('search_result')
    # ### end Alembic commands ###
