"""empty message

Revision ID: 65b3601c0fc9
Revises: 71b85737d682
Create Date: 2021-10-26 20:56:51.801404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65b3601c0fc9'
down_revision = '71b85737d682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cate_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('asin', sa.String(length=15), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('rating_num', sa.Integer(), nullable=True),
    sa.Column('cate_num', sa.String(length=100), nullable=True),
    sa.Column('cate', sa.String(length=100), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('add_cate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cate_name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('cate_num', sa.String(length=20), nullable=False),
    sa.Column('cate_url', sa.String(length=100), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['cate_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('catelog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catelog',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('asin', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('rating_num', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cate_num', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cate', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], name='catelog_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('add_cate')
    op.drop_table('cate_info')
    # ### end Alembic commands ###
