"""empty message

Revision ID: 71b85737d682
Revises: 
Create Date: 2021-10-16 16:55:48.087148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b85737d682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('star', sa.String(length=10), nullable=False),
    sa.Column('author', sa.String(length=1000), nullable=False),
    sa.Column('rating_time', sa.String(length=300), nullable=False),
    sa.Column('rating_title', sa.String(length=2000), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('rtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('username')
    )
    op.create_table('catelog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('asin', sa.String(length=15), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('rating_num', sa.Integer(), nullable=True),
    sa.Column('cate_num', sa.String(length=100), nullable=True),
    sa.Column('cate', sa.String(length=100), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_info',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('goods_name', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('spider_time', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('trace_pd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('rating_num', sa.String(length=20), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=10), nullable=True),
    sa.Column('cate', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.String(length=100), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('pd_info_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['pd_info_id'], ['product_info.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_pd')
    op.drop_table('product_info')
    op.drop_table('catelog')
    op.drop_table('tb_user')
    op.drop_table('sales_data')
    op.drop_table('review')
    # ### end Alembic commands ###
