"""empty message

Revision ID: e160f6419e45
Revises: 65b3601c0fc9
Create Date: 2021-10-26 22:02:44.947715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e160f6419e45'
down_revision = '65b3601c0fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('add_cate_ibfk_1', 'add_cate', type_='foreignkey')
    op.drop_column('add_cate', 'catalog_id')
    op.add_column('cate_info', sa.Column('catelog_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cate_info', 'add_cate', ['catelog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cate_info', type_='foreignkey')
    op.drop_column('cate_info', 'catelog_id')
    op.add_column('add_cate', sa.Column('catalog_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('add_cate_ibfk_1', 'add_cate', 'cate_info', ['catalog_id'], ['id'])
    # ### end Alembic commands ###
